//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.ProxyMigrantes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaisBE", Namespace="http://schemas.datacontract.org/2004/07/AirlineServices")]
    [System.SerializableAttribute()]
    public partial class PaisBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantVuelosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantVuelos {
            get {
                return this.CantVuelosField;
            }
            set {
                if ((this.CantVuelosField.Equals(value) != true)) {
                    this.CantVuelosField = value;
                    this.RaisePropertyChanged("CantVuelos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais {
            get {
                return this.CodPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodPaisField, value) != true)) {
                    this.CodPaisField = value;
                    this.RaisePropertyChanged("CodPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idioma {
            get {
                return this.IdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdiomaField, value) != true)) {
                    this.IdiomaField = value;
                    this.RaisePropertyChanged("Idioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPais {
            get {
                return this.NomPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPaisField, value) != true)) {
                    this.NomPaisField = value;
                    this.RaisePropertyChanged("NomPais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigranteBE", Namespace="http://schemas.datacontract.org/2004/07/AirlineServices")]
    [System.SerializableAttribute()]
    public partial class MigranteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMigranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMigranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPaisNacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomMigranteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisDestinoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMigrante {
            get {
                return this.ApeMigranteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMigranteField, value) != true)) {
                    this.ApeMigranteField = value;
                    this.RaisePropertyChanged("ApeMigrante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMigrante {
            get {
                return this.CodMigranteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMigranteField, value) != true)) {
                    this.CodMigranteField = value;
                    this.RaisePropertyChanged("CodMigrante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPaisNacion {
            get {
                return this.CodPaisNacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodPaisNacionField, value) != true)) {
                    this.CodPaisNacionField = value;
                    this.RaisePropertyChanged("CodPaisNacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNac {
            get {
                return this.FecNacField;
            }
            set {
                if ((this.FecNacField.Equals(value) != true)) {
                    this.FecNacField = value;
                    this.RaisePropertyChanged("FecNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((this.GeneroField.Equals(value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarDestino {
            get {
                return this.LugarDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarDestinoField, value) != true)) {
                    this.LugarDestinoField = value;
                    this.RaisePropertyChanged("LugarDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMigrante {
            get {
                return this.NomMigranteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomMigranteField, value) != true)) {
                    this.NomMigranteField = value;
                    this.RaisePropertyChanged("NomMigrante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumTelefono {
            get {
                return this.NumTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumTelefonoField, value) != true)) {
                    this.NumTelefonoField = value;
                    this.RaisePropertyChanged("NumTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaisDestino {
            get {
                return this.PaisDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisDestinoField, value) != true)) {
                    this.PaisDestinoField = value;
                    this.RaisePropertyChanged("PaisDestino");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMigrantes.IServicioMigrantes")]
    public interface IServicioMigrantes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaPaises", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaPaisesResponse")]
        ClienteWeb.ProxyMigrantes.PaisBE[] ListaPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaPaises", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaPaisesResponse")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE[]> ListaPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ConsultaMaximoMigrantesNacionalidad", ReplyAction="http://tempuri.org/IServicioMigrantes/ConsultaMaximoMigrantesNacionalidadResponse" +
            "")]
        ClienteWeb.ProxyMigrantes.PaisBE ConsultaMaximoMigrantesNacionalidad(string codPaisNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ConsultaMaximoMigrantesNacionalidad", ReplyAction="http://tempuri.org/IServicioMigrantes/ConsultaMaximoMigrantesNacionalidadResponse" +
            "")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE> ConsultaMaximoMigrantesNacionalidadAsync(string codPaisNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesInternacionales", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesInternacionalesResponse")]
        ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesInternacionales(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesInternacionales", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesInternacionalesResponse")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesInternacionalesAsync(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesNacionales", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesNacionalesResponse")]
        ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesNacionales(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesNacionales", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesNacionalesResponse")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesNacionalesAsync(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesPaisesFechas", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesPaisesFechasResponse")]
        ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesPaisesFechas(string codPaisOrigen, string codPaisDestino, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaMigrantesPaisesFechas", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaMigrantesPaisesFechasResponse")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesPaisesFechasAsync(string codPaisOrigen, string codPaisDestino, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaPaisesMigrantes", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaPaisesMigrantesResponse")]
        ClienteWeb.ProxyMigrantes.PaisBE[] ListaPaisesMigrantes(string codPais, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMigrantes/ListaPaisesMigrantes", ReplyAction="http://tempuri.org/IServicioMigrantes/ListaPaisesMigrantesResponse")]
        System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE[]> ListaPaisesMigrantesAsync(string codPais, System.DateTime fecIni, System.DateTime fecFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMigrantesChannel : ClienteWeb.ProxyMigrantes.IServicioMigrantes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMigrantesClient : System.ServiceModel.ClientBase<ClienteWeb.ProxyMigrantes.IServicioMigrantes>, ClienteWeb.ProxyMigrantes.IServicioMigrantes {
        
        public ServicioMigrantesClient() {
        }
        
        public ServicioMigrantesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMigrantesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMigrantesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMigrantesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWeb.ProxyMigrantes.PaisBE[] ListaPaises() {
            return base.Channel.ListaPaises();
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE[]> ListaPaisesAsync() {
            return base.Channel.ListaPaisesAsync();
        }
        
        public ClienteWeb.ProxyMigrantes.PaisBE ConsultaMaximoMigrantesNacionalidad(string codPaisNacimiento) {
            return base.Channel.ConsultaMaximoMigrantesNacionalidad(codPaisNacimiento);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE> ConsultaMaximoMigrantesNacionalidadAsync(string codPaisNacimiento) {
            return base.Channel.ConsultaMaximoMigrantesNacionalidadAsync(codPaisNacimiento);
        }
        
        public ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesInternacionales(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesInternacionales(codPaisNacimiento, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesInternacionalesAsync(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesInternacionalesAsync(codPaisNacimiento, fecIni, fecFin);
        }
        
        public ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesNacionales(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesNacionales(codPaisNacimiento, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesNacionalesAsync(string codPaisNacimiento, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesNacionalesAsync(codPaisNacimiento, fecIni, fecFin);
        }
        
        public ClienteWeb.ProxyMigrantes.MigranteBE[] ListaMigrantesPaisesFechas(string codPaisOrigen, string codPaisDestino, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesPaisesFechas(codPaisOrigen, codPaisDestino, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.MigranteBE[]> ListaMigrantesPaisesFechasAsync(string codPaisOrigen, string codPaisDestino, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaMigrantesPaisesFechasAsync(codPaisOrigen, codPaisDestino, fecIni, fecFin);
        }
        
        public ClienteWeb.ProxyMigrantes.PaisBE[] ListaPaisesMigrantes(string codPais, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaPaisesMigrantes(codPais, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.ProxyMigrantes.PaisBE[]> ListaPaisesMigrantesAsync(string codPais, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListaPaisesMigrantesAsync(codPais, fecIni, fecFin);
        }
    }
}
