//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AerolineaEntities : DbContext
    {
        public AerolineaEntities()
            : base("name=AerolineaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AVION> AVION { get; set; }
        public DbSet<CONTINENTE> CONTINENTE { get; set; }
        public DbSet<LUGAR> LUGAR { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PASAJERO> PASAJERO { get; set; }
        public DbSet<PILOTO> PILOTO { get; set; }
        public DbSet<RESERVACION> RESERVACION { get; set; }
        public DbSet<RUTA> RUTA { get; set; }
        public DbSet<VUELO> VUELO { get; set; }
        public DbSet<vw_MigrantesPaisLugar> vw_MigrantesPaisLugar { get; set; }
        public DbSet<VW_VISITAS> VW_VISITAS { get; set; }
    }
}
