//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVION
    {
        public AVION()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public string COD_AVION { get; set; }
        public string MATRICULA { get; set; }
        public Nullable<int> CAPACIDAD { get; set; }
        public string COD_MARCA { get; set; }
        public string COD_PILOTO { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual PILOTO PILOTO { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
