
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class AVION
{

    public AVION()
    {

        this.VUELO = new HashSet<VUELO>();

    }


    public string COD_AVION { get; set; }

    public string MATRICULA { get; set; }

    public Nullable<int> CAPACIDAD { get; set; }

    public string COD_MARCA { get; set; }

    public string COD_PILOTO { get; set; }



    public virtual MARCA MARCA { get; set; }

    public virtual PILOTO PILOTO { get; set; }

    public virtual ICollection<VUELO> VUELO { get; set; }

}

}
