
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class CONTINENTE
{

    public CONTINENTE()
    {

        this.PAIS = new HashSet<PAIS>();

    }


    public string COD_CONTINENTE { get; set; }

    public string NOM_CONTINENTE { get; set; }



    public virtual ICollection<PAIS> PAIS { get; set; }

}

}
