//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUGAR
    {
        public LUGAR()
        {
            this.RUTA = new HashSet<RUTA>();
            this.RUTA1 = new HashSet<RUTA>();
        }
    
        public string COD_LUGAR { get; set; }
        public string NOMBRE_LUGAR { get; set; }
        public Nullable<double> LATITUD { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public string NOM_AEROPUERTO { get; set; }
        public string COD_PAIS { get; set; }
    
        public virtual ICollection<RUTA> RUTA { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<RUTA> RUTA1 { get; set; }
    }
}
