//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARCA
    {
        public MARCA()
        {
            this.AVION = new HashSet<AVION>();
        }
    
        public string COD_MARCA { get; set; }
        public string NOM_MARCA { get; set; }
        public string DESC_MARCA { get; set; }
    
        public virtual ICollection<AVION> AVION { get; set; }
    }
}
