
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class MARCA
{

    public MARCA()
    {

        this.AVION = new HashSet<AVION>();

    }


    public string COD_MARCA { get; set; }

    public string NOM_MARCA { get; set; }

    public string DESC_MARCA { get; set; }



    public virtual ICollection<AVION> AVION { get; set; }

}

}
