//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public PAIS()
        {
            this.LUGAR = new HashSet<LUGAR>();
            this.PASAJERO = new HashSet<PASAJERO>();
        }
    
        public string COD_PAIS { get; set; }
        public string NOMBRE_PAIS { get; set; }
        public string MONEDA { get; set; }
        public string IDIOMA { get; set; }
        public string COD_CONTINENTE { get; set; }
    
        public virtual CONTINENTE CONTINENTE { get; set; }
        public virtual ICollection<LUGAR> LUGAR { get; set; }
        public virtual ICollection<PASAJERO> PASAJERO { get; set; }
    }
}
