
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class PAIS
{

    public PAIS()
    {

        this.LUGAR = new HashSet<LUGAR>();

        this.PASAJERO = new HashSet<PASAJERO>();

    }


    public string COD_PAIS { get; set; }

    public string NOMBRE_PAIS { get; set; }

    public string MONEDA { get; set; }

    public string IDIOMA { get; set; }

    public string COD_CONTINENTE { get; set; }



    public virtual CONTINENTE CONTINENTE { get; set; }

    public virtual ICollection<LUGAR> LUGAR { get; set; }

    public virtual ICollection<PASAJERO> PASAJERO { get; set; }

}

}
