//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJERO
    {
        public PASAJERO()
        {
            this.RESERVACION = new HashSet<RESERVACION>();
        }
    
        public string COD_PASAJERO { get; set; }
        public string DNI { get; set; }
        public string NOMBRE_PASAJERO { get; set; }
        public string APELLIDO_PASAJERO { get; set; }
        public string SEXO { get; set; }
        public string NUMERO_TELEFONICO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string COD_PAIS { get; set; }
        public string NACIONALIDAD { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<RESERVACION> RESERVACION { get; set; }
    }
}
