
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class PASAJERO
{

    public PASAJERO()
    {

        this.RESERVACION = new HashSet<RESERVACION>();

    }


    public string COD_PASAJERO { get; set; }

    public string DNI { get; set; }

    public string NOMBRE_PASAJERO { get; set; }

    public string APELLIDO_PASAJERO { get; set; }

    public string SEXO { get; set; }

    public string NUMERO_TELEFONICO { get; set; }

    public string EMAIL { get; set; }

    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }

    public string COD_PAIS { get; set; }

    public string NACIONALIDAD { get; set; }



    public virtual PAIS PAIS { get; set; }

    public virtual ICollection<RESERVACION> RESERVACION { get; set; }

}

}
