
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class RESERVACION
{

    public string COD_RESERVACION { get; set; }

    public Nullable<System.DateTime> FECHA_RESERVACION { get; set; }

    public string ESTADO_RESERVACION { get; set; }

    public Nullable<bool> TOMO_VUELO { get; set; }

    public string COD_VUELO { get; set; }

    public string COD_PASAJERO { get; set; }



    public virtual PASAJERO PASAJERO { get; set; }

    public virtual VUELO VUELO { get; set; }

}

}
