//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVACION
    {
        public string COD_RESERVACION { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVACION { get; set; }
        public string ESTADO_RESERVACION { get; set; }
        public Nullable<bool> TOMO_VUELO { get; set; }
        public string COD_VUELO { get; set; }
        public string COD_PASAJERO { get; set; }
    
        public virtual PASAJERO PASAJERO { get; set; }
        public virtual VUELO VUELO { get; set; }
    }
}
