
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class RUTA
{

    public RUTA()
    {

        this.VUELO = new HashSet<VUELO>();

    }


    public string COD_RUTA { get; set; }

    public string NOM_RUTA { get; set; }

    public string DESCRIPCION_RUTA { get; set; }

    public string TIPO_RUTA { get; set; }

    public string COD_ORIGEN { get; set; }

    public string COD_DESTINO { get; set; }



    public virtual LUGAR LUGAR { get; set; }

    public virtual LUGAR LUGAR1 { get; set; }

    public virtual ICollection<VUELO> VUELO { get; set; }

}

}
