//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO
    {
        public VUELO()
        {
            this.RESERVACION = new HashSet<RESERVACION>();
        }
    
        public string COD_VUELO { get; set; }
        public string DESCRIPCION_VUELO { get; set; }
        public Nullable<System.DateTime> FECHA_DESPEQUE { get; set; }
        public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }
        public Nullable<System.TimeSpan> HORA_DESPEGUE { get; set; }
        public Nullable<System.TimeSpan> HORA_LLEGADA { get; set; }
        public Nullable<bool> ESTADO_VUELO { get; set; }
        public Nullable<decimal> PRECIO_VUELO { get; set; }
        public string COD_AVION { get; set; }
        public string COD_RUTA { get; set; }
    
        public virtual AVION AVION { get; set; }
        public virtual ICollection<RESERVACION> RESERVACION { get; set; }
        public virtual RUTA RUTA { get; set; }
    }
}
