
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class VUELO
{

    public VUELO()
    {

        this.RESERVACION = new HashSet<RESERVACION>();

    }


    public string COD_VUELO { get; set; }

    public string DESCRIPCION_VUELO { get; set; }

    public Nullable<System.DateTime> FECHA_DESPEQUE { get; set; }

    public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }

    public Nullable<System.TimeSpan> HORA_DESPEGUE { get; set; }

    public Nullable<System.TimeSpan> HORA_LLEGADA { get; set; }

    public Nullable<bool> ESTADO_VUELO { get; set; }

    public Nullable<decimal> PRECIO_VUELO { get; set; }

    public string COD_AVION { get; set; }

    public string COD_RUTA { get; set; }



    public virtual AVION AVION { get; set; }

    public virtual ICollection<RESERVACION> RESERVACION { get; set; }

    public virtual RUTA RUTA { get; set; }

}

}
