//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MigrantesPaisLugar
    {
        public string COD_PASAJERO { get; set; }
        public string NOMBRE_PASAJERO { get; set; }
        public string APELLIDO_PASAJERO { get; set; }
        public string DNI { get; set; }
        public string EMAIL { get; set; }
        public string NUMERO_TELEFONICO { get; set; }
        public string SEXO { get; set; }
        public string DESCRIPCION_VUELO { get; set; }
        public string COD_PAIS_ORIGEN { get; set; }
        public string PAIS_ORIGEN { get; set; }
        public string COD_PAIS_DESTINO { get; set; }
        public string PAIS_DESTINO { get; set; }
        public string COD_ORIGEN { get; set; }
        public string NOMBRE_ORIGEN { get; set; }
        public string COD_DESTINO { get; set; }
        public string NOMBRE_DESTINO { get; set; }
    }
}
