
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirlineServices
{

using System;
    using System.Collections.Generic;
    
public partial class VW_VISITAS
{

    public string COD_PASAJERO { get; set; }

    public string DNI { get; set; }

    public string NOMBRE_PASAJERO { get; set; }

    public string APELLIDO_PASAJERO { get; set; }

    public string SEXO { get; set; }

    public string NUMERO_TELEFONICO { get; set; }

    public string NACIONALIDAD { get; set; }

    public string EMAIL { get; set; }

    public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }

    public string COD_RESERVACION { get; set; }

    public string COD_VUELO { get; set; }

    public Nullable<System.DateTime> FECHA_RESERVACION { get; set; }

    public string COD_RUTA { get; set; }

    public string ESTADO_RESERVACION { get; set; }

    public Nullable<bool> TOMO_VUELO { get; set; }

    public string DESCRIPCION_VUELO { get; set; }

    public string COD_AVION { get; set; }

    public Nullable<System.DateTime> FECHA_DESPEQUE { get; set; }

    public Nullable<System.DateTime> FECHA_LLEGADA { get; set; }

    public Nullable<System.TimeSpan> HORA_DESPEGUE { get; set; }

    public Nullable<System.TimeSpan> HORA_LLEGADA { get; set; }

    public Nullable<bool> ESTADO_VUELO { get; set; }

    public Nullable<decimal> PRECIO_VUELO { get; set; }

    public string COD_DESTINO { get; set; }

    public string COD_ORIGEN { get; set; }

    public string DESCRIPCION_RUTA { get; set; }

    public string NOM_RUTA { get; set; }

    public string TIPO_RUTA { get; set; }

}

}
